{
  "openapi": "3.0.0",
  "info": {
    "title": "Admin-Management APIs",
    "description": "APIs for the Admins to manage.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://apis.indyauction.net/dev/v1/admin-management"
    }
  ],
  "tags": [
    {
      "name": "Admin management",
      "description": "APIs to manage the Admin"
    }
  ],

  "paths": {
    "/auctions": {
      "get": {
        "tags": [
          "Admin Auction Management"
          
        ],
        "summary": "Listing auction",
        "description": "Listing auction",
        "parameters": [
          {
            "name": "start_date",
            "in": "query",
            "description": "Filter by date range, this is the start date",
            "schema": {
              "type": "number"
            },
            "example": 1701082800000
          },
          {
            "name": "end_date",
            "in": "query",
            "description": "Filter by date range, this is the end date",
            "schema": {
              "type": "number"
            },
            "example": 1701088200000
          },
          {
            "name": "status",
            "in": "query",
            "description": "Filter by status",
            "schema": {
              "type": "string"
            },
            "example": "Draft"
          },
          {
            "name": "sort",
            "in": "query",
            "description": "If sort is opted",
            "schema": {
              "type": "string"
            },
            "example": "true"
          },
          {
            "name": "key",
            "in": "query",
            "description": "Sort by key",
            "schema": {
              "type": "string"
            },
            "example": "title"
          },
          {
            "name": "order",
            "in": "query",
            "description": "ascending or descending",
            "schema": {
              "type": "string"
            },
            "example": "ascending"
          },
          {
            "name": "page",
            "in": "query",
            "description": "Filter by status",
            "schema": {
              "type": "integer"
            },
            "example": 1
          },
          {
            "name": "keyword",
            "in": "query",
            "description": "ascending or descending",
            "schema": {
              "type": "string"
            },
            "example": "C"
          }

        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved auctions",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { 
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "auction_id": {
                            "type": "string"
                          },
                          "title": {
                            "type": "number"
                          },
                          "start_date": {
                            "type": "number"
                          },
                          "end_date": {
                            "type": "string"
                          },
                          "status": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "auction_image": {
                            "type": "string"
                          },
                          "description": {
                            "type": "string"
                          },
                          "currency": {
                            "type": "string"
                          },
                          "extension_type": {
                            "type": "string"
                          },
                          "extension_time": {
                            "type": "string"
                          },
                          "extension_time_between_lots": {
                            "type": "string"
                          },
                          "registration_type": {
                            "type": "string"
                          },
                          "add_buyer_fees": {
                            "type": "string"
                          },
                          "time_zone": {
                            "type": "string"
                          },
                          "make_your_auction_private": {
                            "type": "string"
                          },
                          "passcode": {
                            "type": "string"
                          },
                          "fees": {
                            "type": "string"
                          },
                          "seller_email": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "total_records_found": {
                      "type": "integer"
                    },
                    "total_auctions": {
                      "type": "integer"
                    },
                    "current_page": {
                      "type": "integer"
                    },
                    "total_pages": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                        "data": [
                          {
                            "auction_id": "A0169",
                            "title": "Auction Event",
                            "start_date": 1701082800000,
                            "end_date": 1701088200000,
                            "status": "Draft",
                            "created_at": "2023-08-31 10:27:57.993000",
                            "auction_image": "",
                            "description": "",
                            "currency": "",
                            "extension_type": "",
                            "extension_time": "",
                            "extension_time_between_lots": "",
                            "registration_type": "",
                            "add_buyer_fees": "",
                            "time_zone": "",
                            "make_your_auction_private": "",
                            "passcode": "",
                            "fees": ""
                                                    }
                        ],
                        "total_records_found": 1,
                        "total_auctions": 1,
                        "current_page": 1,
                        "total_pages": 1
                      }
                
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "example": "You do not have access to perform this API action"
                      
                    }
                  }    
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/buyers":{
      "get": {
        "tags": [
          "Admin Buyers Management"
          
        ],
        "summary": "Listing Buyers",
        "description": "Listing Buyers",
        "parameters": [
          {
            "name": "sort_key",
            "in": "query",
            "description": "Sort by key",
            "schema": {
              "type": "string"
            },
            "example": "full_name"
          },
          {
            "name": "sort_order",
            "in": "query",
            "description": "ascending or descending",
            "schema": {
              "type": "string"
            },
            "example": "ascending"
          },
          {
            "name": "page_number",
            "in": "query",
            "description": " page number",
            "schema": {
              "type": "integer"
            },
            "example": 1
          },
          {
            "name": "search",
            "in": "query",
            "description": "search key",
            "schema": {
              "type": "string"
            },
            "example": "C"
          }

        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved auctions",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { 
                    "buyers": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "_id": {
                            "type": "string"
                          },
                          "email_address": {
                            "type": "number"
                          },
                          "seller_email": {
                            "type": "string"
                          },
                          "first_name": {
                            "type": "number"
                          },
                          "last_name": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "total_buyers": {
                      "type": "integer"
                    },
                    "page_number": {
                      "type": "integer"
                    },
                    "page_size": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                        "buyers": [
                          {
                            "_id": "6543d8bda6b97ebf494c7424",
                            "email_address": "sthuthi+127@7edge.com",
                            "full_name": "sthuthi ",
                            "seller_email": "sthuthi+127@7edge.com"
                          }
                        ],
                        "total_buyers": 1,
                        "page_number": 1,
                        "page_size": 1
                      }
                
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "example": "You do not have access to perform this API action"
                      
                    }
                  }    
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }

    },
    "/buyer-auctions":{
      "get": {
        "tags": [
          "Admin Buyers Management"
          
        ],
        "summary": "Buyers list auctions",
        "description": "Buyers list auctions",
        "parameters": [
          {
            "name": "sort_by",
            "in": "query",
            "description": "Sort by key",
            "schema": {
              "type": "string"
            },
            "example": "created_at"
          },
          {
            "name": "sort_order",
            "in": "query",
            "description": "ascending or descending",
            "schema": {
              "type": "string"
            },
            "example": "ascending"
          },
          {
            "name": "page_number",
            "in": "query",
            "description": " page number",
            "schema": {
              "type": "integer"
            },
            "example": 1
          },
          {
            "name": "buyer_id",
            "in": "query",
            "description": "buyer_id",
            "schema": {
              "type": "string"
            },
            "example": "656cb04247790c35822dfb46"
          }

        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved auctions",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { 
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "_id":{
                            "type": "string"
                          },
                          "email_address":{
                            "type": "string"
                          },
                          "seller_email":{
                            "type": "string"
                          },
                          "created_at":{
                            "type": "string"
                          },
                          "seller_name":{
                            "type": "string"
                          },
                          "auction_id":{
                            "type": "string"
                          },
                          "status":{
                            "type": "string"
                          },
                          "title":{
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "data": [
                    {
                      "_id": "6571f41aefbc19e0753d3596",
                      "email_address": "murali.r@7edge.com",
                      "seller_email": "anusha.k+indyauction@7edge.com",
                      "created_at": "2023-12-07 16:34:34.017000",
                      "seller_name": "Addison Hintz",
                      "auction_id": "A0395",
                      "status": "Published",
                      "title": "Opportunities for Artists"
                    },
                    {
                      "_id": "6575e03859e65d8e6baf5d4b",
                      "email_address": "murali.r@7edge.com",
                      "seller_email": "anusha.k+indyauction@7edge.com",
                      "created_at": "2023-12-10 15:58:48.659000",
                      "seller_name": "Addison Hintz",
                      "auction_id": "A0423",
                      "status": "Published",
                      "title": "Opportunities for Artists"
                    }
                  ]
                      }
                
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "example": "You do not have access to perform this API action"
                      
                    }
                  }    
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }

    },
    "/buyer-details":{
      "get": {
        "tags": [
          "Admin Buyers Management"
          
        ],
        "summary": "Buyer Details",
        "description": "Buyers Details",
        "parameters": [
          {
            "name": "buyer_id",
            "in": "query",
            "description": "buyer id",
            "schema": {
              "type": "string"
            },
            "example": "656cb04247790c35822dfb46"
          }

        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved buyer detail",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string"
                    },
                    "email_address":{
                      "type": "string"
                    },
                    "first_name": {
                      "type": "string"
                    },
                    "last_name": {
                      "type": "string"
                    },
                    "country_code": {
                      "type": "string"
                    },
                    "phone_number":  {
                      "type": "string"
                    },
                    "address_line1":  {
                      "type": "string"
                    },
                    "address_line2": {
                      "type": "string"
                    },
                    "country": {
                      "type": "string"
                    },
                    "is_manual": {
                      "type": "string"
                    },
                    "postal_code":  {
                      "type": "string"
                    },
                    "town/city": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  
                    "_id": "656cb04247790c35822dfb46",
                    "email_address": "murali.r@7edge.com",
                    "first_name": "murali",
                    "last_name": "e",
                    "country_code": "+91",
                    "phone_number": "22222226666666666662",
                    "address_line1": "Kolar Rd",
                    "address_line2": "",
                    "country": "India",
                    "is_manual": "False",
                    "postal_code": "",
                    "town/city": "Bhopal"
                  
                      }
                
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "example": "You do not have access to perform this API action"
                      
                    }
                  }    
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }

    },
    "/{id}":{
      "get": {
        "tags": [
          "Admin Buyers Management"
          
        ],
        "summary": "Buyer purchases Details",
        "description": "Buyers purchases details",
        "parameters": [
          {
            "name": "buyer_id",
            "in": "path",
            "description": "buyer id",
            "schema": {
              "type": "string"
            },
            "example": "659393fff55ff30b3ff4221b"
          },
          {
            "name": "sort_by",
            "in": "query",
            "description": "sorting by key",
            "schema": {
              "type": "string"
            },
            "example": "created_at"
          },
          {
            "name": "sort_order",
            "in": "query",
            "description": "sorting by descending or ascending order",
            "schema": {
              "type": "string"
            },
            "example": "descending"
          }, 
          {
            "name": "page_number",
            "in": "query",
            "description": "page number",
            "schema": {
              "type": "string"
            },
            "example": "1"
          },
          {
            "name": "per_page",
            "in": "query",
            "description": "page size",
            "schema": {
              "type": "string"
            },
            "example": "3"
          }

        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved buyer detail",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "data": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "_id": {
                          "type": "string"
                        },
                        "payment_status":{
                          "type": "string"
                        },
                        "amount": {
                          "type": "string"
                        },
                        "payment": {
                          "type": "string"
                        },
                        "currency": {
                          "type": "string"
                        },
                        "order_number":  {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "integer"
                        },
                        "auction_title": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "total_pages": {
                    "type": "integer"
                  },
                  "total_records": {
                    "type": "integer"
                  },
                  "current_page": {
                    "type": "integer"
                  }
                },
                "example": {
                  "data": [
                      {
                          "_id": "6597c5eb39a8d47e3b1864b4",
                          "payment_status": "Unpaid",
                          "amount": 5650,
                          "payment": "Stripe",
                          "currency": "INR",
                          "order_number": "OD001",
                          "created_at": 1704445417,
                          "auction_title": "The Classic Auction - Sample",
                          "name": "AnushaK"
                      },
                      {
                          "_id": "658188165dc1e7991cd3de21",
                          "payment_status": "Paid",
                          "amount": 22000,
                          "payment": "Stripe",
                          "currency": "CAD",
                          "order_number": "OD005",
                          "created_at": 1702987796,
                          "auction_title": "The Ceramics & Craft Auction"
                      },
                      {
                          "_id": "6581838030a8395d8449f1c0",
                          "payment_status": "Unpaid",
                          "amount": 22000,
                          "payment": "Stripe",
                          "currency": "CAD",
                          "order_number": "OD004",
                          "created_at": 1702986621,
                          "auction_title": "The Ceramics & Craft Auction"
                      }
                  ],
                  "total_pages": 11,
                  "total_records": 33,
                  "current_page": 1
                }
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "example": "You do not have access to perform this API action"
                      
                    }
                  }    
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }

    },
    "/clone-auction": {
      "post": {
        "tags": [
          "Admin Buyers Management"
        ],
        "summary": "Auction cloned",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "auction_id":{
                    "type": "string"
                  },
                  "seller_email":{
                    "type": "string"
                  }
            },
            "example": {
               "object_id": "65a7bf0da3ae6e71fccd6252"
              }
            }
          }
        }
      },
        "responses": {
          "201":{
            "description": "Success",
            "content": {
              "application/json": {
                "example":{
                  "message": "Auction has been cloned successfully"
                }
                }
              }
            },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "You do not have access to perform this API action"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Auction with given ID not found"
                    }
                  }
                  }
                }
              }
            }
          }
        } 
    },
    "/order-details": {
      "get": {
        "tags": [
          "Admin Buyers Management"
        ],
        "summary": "Complete Order Details",
        "description": "Order details",
        "parameters": [
          {
            "name": "order_id",
            "in": "query",
            "description": "order_id",
            "schema": {
              "type": "string"
            },
            "example": "65a13c3265e68545fe2f9b38"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved complete order details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "data": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "email_address": {
                        "type": "string"
                      },
                      "payment_intent": {
                        "type": "string"
                      },
                      "status": {
                        "type": "string"
                      },
                      "payment_status": {
                        "type": "string"
                      },
                      "amount": {
                        "type": "number"
                      },
                      "payment": {
                        "type": "string"
                      },
                      "seller_email": {
                        "type": "string"
                      },
                      "shipping_address": {
                        "type": "object",
                        "properties": {
                          "_id": {
                            "type": "string"
                          },
                          "first_name": {
                            "type": "string"
                          },
                          "last_name": {
                            "type": "string"
                          },
                          "address_line1": {
                            "type": "string"
                          },
                          "address_line2": {
                            "type": "string"
                          },
                          "city": {
                            "type": "string"
                          },
                          "state": {
                            "type": "string"
                          },
                          "postal_code": {
                            "type": "string"
                          },
                          "country": {
                            "type": "string"
                          },
                          "type": {
                            "type": "string"
                          },
                          "default": {
                            "type": "boolean"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "email_address": {
                            "type": "string"
                          }
                        }
                      },
                      "billing_address": {
                        "type": "object",
                        "properties": {
                          "_id": {
                            "type": "string"
                          },
                          "first_name": {
                            "type": "string"
                          },
                          "last_name": {
                            "type": "string"
                          },
                          "address_line1": {
                            "type": "string"
                          },
                          "address_line2": {
                            "type": "string"
                          },
                          "city": {
                            "type": "string"
                          },
                          "state": {
                            "type": "string"
                          },
                          "postal_code": {
                            "type": "string"
                          },
                          "country": {
                            "type": "string"
                          },
                          "type": {
                            "type": "string"
                          },
                          "default": {
                            "type": "boolean"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "email_address": {
                            "type": "string"
                          }
                        }
                      },
                    "order_number": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "auction_title": {
                      "type": "string"
                    },
                    "purchases": {
                      "type": "array",
                      "items": {
                        "type":"object",
                        "properties": {
                          "bid_amount": {
                            "type": "number"
                          },
                          "fees": {
                            "type": "string"
                          },
                          "seller_email": {
                            "type": "string"
                          },
                          "percentage": {
                            "type": "string"
                          },
                          "lot_title": {
                            "type": "string"
                          },
                          "lot_number": {
                            "type": "string"
                          },
                          "lot_image": {
                            "type": "string"
                          },
                          "auction_id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "currency": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "approved_status": {
                      "type": "string"
                    }
                  }
                },
                "example":{
                  "data": {
                      "_id": "65a13c3265e68545fe2f9b38",
                      "email_address": "anusha.k+theauction@7edge.com",
                      "payment_intent": "pi_3OXkdBFqJJvX3IOZ0QWciNbz",
                      "status": "succeeded",
                      "payment_status": "Paid",
                      "amount": 2665,
                      "payment": "Stripe",
                      "seller_email": "anusha.k+sdet@7edge.com",
                      "shipping_address": {
                          "_id": "65a12236563aa7ed2c442f7a",
                          "first_name": "Anusha",
                          "last_name": "K",
                          "address_line1": "Israel Aharoni St",
                          "address_line2": "Israel Aharoni Street",
                          "city": "Jerusalem",
                          "state": "Jerusalem District",
                          "postal_code": "",
                          "country": "Israel",
                          "type": "shipping",
                          "default": true,
                          "created_at": "2024-01-12 11:27:50.919000",
                          "email_address": "anusha.k+theauction@7edge.com"
                      },
                      "billing_address": {
                          "_id": "65a12236563aa7ed2c442f7a",
                          "first_name": "Anusha",
                          "last_name": "K",
                          "address_line1": "Israel Aharoni St",
                          "address_line2": "Israel Aharoni Street",
                          "city": "Jerusalem",
                          "state": "Jerusalem District",
                          "postal_code": "",
                          "country": "Israel",
                          "type": "shipping",
                          "default": true,
                          "created_at": "2024-01-12 11:27:50.919000",
                          "email_address": "anusha.k+theauction@7edge.com"
                      },
                      "order_number": "OD002",
                      "created_at": 1705065519,
                      "auction_title": "Opportunities for Artist",
                      "purchases": [
                          {
                              "bid_amount": 320,
                              "fees": "2345",
                              "percentage": "",
                              "lot_title": "sample3",
                              "lot_number": 3,
                              "lot_image": "DomainName/Auctions/lots/images/97168780-af3b-93aa-5d72-b191d32aef83/demo_image5.jpg",
                              "auction_id": "65a136ec40ddb9865b1df4c5",
                              "name": "The Auction Collective",
                              "currency": "GBP"
                          }
                      ],
                      "approved_status": "Approved"
                  }
                }
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "example": "You do not have access to perform this API action"
                      
                    }
                  }    
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header",
        "description": "Bearer Token"
      }
    }
  }
}
