{
    "openapi": "3.0.0",
    "info": {
      "title": "Auction Management APIs",
      "description": "Auction APIs to create the API's",
      "contact": {
        "name": "no-reply@indy.auction",
        "email": "no-reply@indy.auction"
      },
      "version": "1.0.0"
    },
    "servers": [
      {
        "url": "https://apis.indyauction.net/dev/v1/auctions"
      }
    ],
    "tags": [
      {
          "name": "Auction Management",
          "description": "APIs to manage the auctions list"
      }
    ],
    "paths": {
      "/":{
        "post": {
          "tags": [
            "create"
          ],
          "summary": "Auction create",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Auction"
              },
              "example": {
                "auction_id": "A001",
                "seller_email": "seller@example.com",
                "created_at": "2023-08-24",
                "updated_at": "2023-08-25",
                "template_name": "Auction Template 1",
                "menu_links": [
                  {
                    "title": "Home",
                    "link_url": "https://example.com/home",
                    "dropdown": [
                      {
                        "title": "About Us",
                        "link_url": "https://example.com/about"
                      },
                      {
                        "title": "Contact Us",
                        "link_url": "https://example.com/contact"
                      }
                    ]
                  }
                ],
                "logo_image": "https://example.com/logo.png",
                "logo_redirection_url": "https://example.com",
                "auction_title": "Auction Event",
                  "auction_image": "https://example.com/auction-image.png",
                  "auction_description": "Join our exciting auction event!",
                  "currency": "USD",
                  "start_date": 1669966800,
                  "start_time": "10:00",
                  "end_date": 1669966800,
                  "end_time": "6:00",
                "note": "asda",
                "extension_type": "Automatic",
                "extension_time": "5 minutes",
                "registration_type": "Open",
                "add_buyer_fees": "10%",
                "faq": [
                  {
                    "add_question": "How do I participate?",
                    "add_answer": "Register on our website and place bids."
                  },
                  {
                    "add_question": "What payment methods are accepted?",
                    "add_answer": "We accept credit cards and PayPal."
                  }
                ],
                "time_zone": "UTC+5:30",
                "terms_and_condition": "By participating, you agree to our terms.",
                "publish_auction_results": true,
                "show_bidder_location_in_bidder_history": true, 
                "make_your_auction_private": true,
                "passcode": "1234",
                "font": {
                  "hearder_font": "Arial",
                  "body_font": "Helvetica"
                },
                "buttons": {
                  "background_color": "#007BFF",
                  "text_color": "#FFFFFF"
                },
                "header": {
                  "background_color": "#F2F2F2",
                  "text_color": "#333333"
                },
                "content_area": {
                  "background_color": "#FFFFFF",
                  "text_color": "#555555"
                },
                "footer": {
                  "background_color": "#333333",
                  "text_color": "#FFFFFF"
                },
                "paddle": {
                  "background_color": "#FFD700",
                  "text_color": "#333333"
                },
                "status": "Active"
              }
              
            }
          }
        },
          "responses": {
            "201":{
              "description": "Success",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object"
                  }
                }
              }
            },
            "500": {
              "description": "Internal server error",
              "content": {
                "application/json": {
                  "examples": {
                    "example1": {
                      "value": {
                        "message": "Internal server error"
                      }
                    }
                  }
                }
              }
            },
            "400": {
              "description": "Bad Request",
              "content": {
                "application/json": {
                  "examples": {
                    "example1": {
                      "value": {
                        "message": "Validation failed"
                      }
                    },
                    "example2":{
                      "value":{
                        "message":"Please upgrade"
                      }
                    },
                    "example3":{
                      "value":{
                        "message":"Something went wrong"
                      }
                    },
                    "example4":{
                      "value":{
                        "message":"Invalid request"
                      }
                    }
                  }
                }
              }
            }
          }
        },
      "get": {
          "tags": [
            "create"
          ],
          "summary": "Listing auction",
          "description": "Listing auction",
          "parameters": [
            {
              "name": "start_date",
              "in": "query",
              "description": "Filter by date range, this is the start date",
              "schema": {
                "type": "string",
                "format": "date"
              },
              "example": "2023-08-30"
            },
            {
              "name": "end_date",
              "in": "query",
              "description": "Filter by date range, this is the end date",
              "schema": {
                "type": "string",
                "format": "date"
              },
              "example": "2023-08-30"
            },
            {
              "name": "status",
              "in": "query",
              "description": "Filter by status",
              "schema": {
                "type": "string"
              },
              "example": "complete"
            }
          ],
          "responses": {
            "200": {
              "description": "Successfully retrieved auctions",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Auction"
                  },
                  "example": {
                    "example": {
                      "auction_id": "A001",
                      "seller_email": "seller@example.com",
                      "created_at": "2023-08-24",
                      "updated_at": "2023-08-25",
                      "template_name": "Auction Template 1",
                      "menu_links": [
                        {
                          "title": "Home",
                          "link_url": "https://example.com/home",
                          "dropdown": [
                            {
                              "title": "About Us",
                              "link_url": "https://example.com/about"
                            },
                            {
                              "title": "Contact Us",
                              "link_url": "https://example.com/contact"
                            }
                          ]
                        }
                      ],
                      "logo_image": "https://example.com/logo.png",
                      "logo_redirection_url": "https://example.com",
                      "auction_title": "Auction Event",
                        "auction_image": "https://example.com/auction-image.png",
                        "auction_description": "Join our exciting auction event!",
                        "currency": "USD",
                        "start_date": 1669966800,
                        "start_time": "10:00",
                        "end_date": 1669966800,
                        "end_time": "6:00",
                      "note": "asda",
                      "extension_type": "Automatic",
                      "extension_time": "5 minutes",
                      "registration_type": "Open",
                      "add_buyer_fees": "10%",
                      "faq": [
                        {
                          "add_question": "How do I participate?",
                          "add_answer": "Register on our website and place bids."
                        },
                        {
                          "add_question": "What payment methods are accepted?",
                          "add_answer": "We accept credit cards and PayPal."
                        }
                      ],
                      "time_zone": "UTC+5:30",
                      "terms_and_condition": "By participating, you agree to our terms.",
                      "publish_auction_results": true,
                      "show_bidder_location_in_bidder_history": true, 
                      "make_your_auction_private": true,
                      "passcode": "1234",
                      "font": {
                        "hearder_font": "Arial",
                        "body_font": "Helvetica"
                      },
                      "buttons": {
                        "background_color": "#007BFF",
                        "text_color": "#FFFFFF"
                      },
                      "header": {
                        "background_color": "#F2F2F2",
                        "text_color": "#333333"
                      },
                      "content_area": {
                        "background_color": "#FFFFFF",
                        "text_color": "#555555"
                      },
                      "footer": {
                        "background_color": "#333333",
                        "text_color": "#FFFFFF"
                      },
                      "paddle": {
                        "background_color": "#FFD700",
                        "text_color": "#333333"
                      },
                      "status": "Active"
                    }
                  }
                }
              }
            },
            "400": {
              "description": "Bad Request",
              "content": {
                "application/json": {
                  "examples": {
                    "example1": {
                      "value": {
                        "message": {
                          "type": "string",
                          "example": "Something went wrong"
                        }
                      }
                    }    
                  }
                }
              }
            },
            "500": {
              "description": "Internal Server Error",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "properties": {
                      "message": {
                        "type": "string",
                        "example": "Internal server error"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }

    },
    "components": {
      "schemas": {
        "Auction": {
          "type": "object",
          "properties": {
            "seller_email":{
              "type": "string"
            },
            "auction_id":{
              "type": "string"
            },
            "template_name":{
              "type": "string"
            },
            "note": {
              "type": "string"
            },
            "menu_links":{
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "link_url": {
                    "type": "string"
                  },
                  "dropdown": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "title" :{
                          "type": "string"
                        },
                        "link_url": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            },
            "logo_image":{
              "type": "string"
            },
            "logo_redirection_url":{
              "type": "string"
            },
            "auction_name":{
              "type": "string"
            },
            "auction_image":{
              "type": "string"
            },
            "auction_description":{
              "type": "string"
            },
            "currency":{
              "type": "string"
            },
            
            "auction_date":{
              "type": "string"
            },
            "start_date":{
              "type": "number"
            },
            "start_time":{
              "type": "number"
            },
            "end_date":{
              "type": "number"
            },
            "end_time":{
              "type": "number"
            },
            "extension_type":{
              "type": "string"
            },
            "extension_time":{
              "type": "string"
            },
            "registration_type":{
              "type": "string"
            },
            "add_buyer_fees":{
              "type": "number"
            },
            "time_zone" :{
              "type": "string"
            },
            "faq":{
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "add_question": {
                    "type": "string"
                  },
                  "add_answer": {
                    "type": "string"
                  }
                }
              }
            },
            "terms_and_condition":{
              "type": "string"
            },
            "publish_auction_result":{
              "type": "boolean"
            },
            "show_bidder_location_in_bidder_history":{
              "type": "boolean"
            },
            "make_your_auction_private":{
              "type": "boolean"
            },
            "passcode":{
              "type": "string"
            },
            "font":{
              "type": "object"
            },
            "button":{
              "type": "object"
            },
            "header":{
              "type": "object"
            },
            "content_area":{
              "type": "object"
            },
            "footer":{
              "type": "object"
            },
            "paddle":{
              "type": "object"
            },
            "status":{
              "type": "string"
            }
        }
        },
        "Error": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string"
            }
          }
        }
      },
      "securitySchemes": {
        "BearerAuth": {
          "type": "apiKey",
          "name": "Authorization",
          "in": "header",
          "description": "Bearer Token"
        }
      }
    }
  }
  