{
  "openapi": "3.0.0",
  "info": {
    "title": "In Person Auction Management APIs",
    "description": "Auction APIs to create the API's",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://apis.dev.indyauction.net/v1/in-person-auction"
    }
  ],
  "tags": [
    {
      "name": "Auction Management",
      "description": "APIs to manage the auctions list"
    }
  ],
  "paths": {
    "/": {
      "post": {
        "tags": ["Auction"],
        "summary": "Auction create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Auction"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "message": "Auction created successfully",
                  "auctions_id": "A0362"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Something went wrong. Please try again!"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/view":{
      "get": {
        "tags": [
          "Auction"
        ],
        "servers": [
            {
              "url": "https://apis.dev.indyauction.net/v1/auctions"
            }
          ],
        "summary": "View auction details",
        "description": "View auction in detail",
        "parameters": [
          {
            "name": "auction_id",
            "in": "query",
            "description": "Fetch details for the provided auction id",
            "schema": {
              "type": "string"
            },
            "example": "68789f366b759c17f795ce47"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved auction details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { 
                    "data": {
                      "type": "object",
                      "properties": {
                        "auction_id": {
                          "type": "string"
                        },
                        "title": {
                          "type": "string"
                        },
                        "start_date": {
                          "type": "number"
                        },
                        "status": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "auction_image": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "currency": {
                          "type": "string"
                        },
                        "registration_type": {
                          "type": "string"
                        },
                        "add_buyer_fees": {
                          "type": "string"
                        },
                        "time_zone": {
                          "type": "string"
                        },
                        "make_your_auction_private": {
                          "type": "string"
                        },
                        "passcode": {
                          "type": "string"
                        },
                        "fees": {
                          "type": "string"
                        },
                        "auctioin_type": {
                          "type": "string"
                        },
                        "font": {
                          "type": "object",
                          "properties": {
                            "hearder_font": {
                              "type": "string"
                            },
                            "body_font": {
                              "type": "string"
                            }
                          }
                        },
                        "button": {
                          "type": "object",
                          "properties": {
                            "background_color": {
                              "type": "string"
                            },
                            "text_color": {
                              "type": "string"
                            }
                          }
                        },
                        "header": {
                          "type": "object",
                          "properties": {
                            "background_color": {
                              "type": "string"
                            },
                            "text_color": {
                              "type": "string"
                            }
                          }
                        },
                        "content_area": {
                          "type": "object",
                          "properties": {
                            "background_color": {
                              "type": "string"
                            },
                            "text_color": {
                              "type": "string"
                            }
                          }
                        },
                        "footer": {
                          "type": "object",
                          "properties": {
                            "background_color": {
                              "type": "string"
                            },
                            "text_color": {
                              "type": "string"
                            },
                            "paddle": {
                              "type": "object",
                              "properties": {
                                "background_color": {
                                  "type": "string"
                                },
                                "text_color": {
                                  "type": "string"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                        "data": {
                            "auction_id": "A29084",
                            "seller_email": "sthuthi+testing@7edge.com",
                            "seller_name": "sandhyashri",
                            "template_name": "Classic",
                            "menu_links": [],
                            "logo_image": "",
                            "logo_redirection_url": "",
                            "title": "Draft auction",
                            "auction_image": "",
                            "description": "",
                            "currency": "USD",
                            "start_date": null,
                            "registration_type": "Email only",
                            "add_buyer_fees": "No additional fees",
                            "faq": [],
                            "time_zone": "",
                            "terms_and_condition": "",
                            "toggle_powered_by_indy": false,
                            "make_your_auction_private": false,
                            "passcode": "",
                            "font": {
                              "hearder_font": "",
                              "body_font": ""
                            },
                            "buttons": {
                              "background_color": "",
                              "text_color": ""
                            },
                            "header": {
                              "background_color": "",
                              "text_color": ""
                            },
                            "content_area": {
                              "background_color": "",
                              "text_color": ""
                            },
                            "footer": {
                              "background_color": "",
                              "text_color": ""
                            },
                            "paddle": {
                              "background_color": "",
                              "text_color": ""
                            },
                            "status": "Draft",
                            "percentage": "",
                            "fees": "",
                            "location": {
                              "address": "",
                              "latitude": "",
                              "longitude": ""
                            },
                            "accept_absentee_bids": false,
                            "accept_telephone_bids": false,
                            "auction_type": "live",
                            "created_at":  "2025-07-17T06:59:02.560Z",
                            "updated_at":  "2025-07-17T06:59:02.560Z",
                            "__v": 0
                          }
                      }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Please provide auction_id"
                      
                    }
                  }    
                }
              }
            }
          },
          "403": {
            "description": "forbidden",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "message": "You do not have access to perform this API action"
                      
                    }
                  }    
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                        "message": "Auction with associated auction_id doesn't exists"
                      
                    }
                  }    
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "There was an error "
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/{auction_id}": {

        "patch": {
          "tags": ["Auction"],
          "summary": "Auction update",
          "description": "Allows editing auction details. Certain fields are restricted once the auction is published.",
          "parameters": [
                {
                  "name": "auction_id",
                  "in": "path",
                  "required": true,
                  "schema": {
                    "type": "string"
                  },
                  "example": "A29098"
                }
              ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "faq": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "question": {
                            "type": "string"
                          },
                          "answer": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "title": {
                      "type": "string"
                    },
                    "terms_and_condition": {
                      "type": "string",
                      "description": "Read-only once auction is published.",
                    },
                    "currency": {
                      "type": "string",
                      "description": "Read-only once auction is published."
                    },
                    "registration_type": {
                      "type": "string",
                      "description": "Read-only once auction is published.",
                    },
                    "add_buyer_fees":{
                      "type": "string"
                    },
                    "fees": {
                      "type": "number",
                      "description": "Read-only once auction is published.",
                    },
                    "percentage": {
                      "type": "string"
                    },
                    "start_date": {
                      "type": "number",
                      "description": "Allowed in both draft and published. Must not be in the past."
                    },
                    "menu_links": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "title": {
                            "type": "string"
                          },
                          "link_url": {
                            "type": "string"
                          },
                          "dropdown": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "title": {
                                  "type": "string"
                                },
                                "link_url": {
                                  "type": "string"
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "location": {
                      "type": "object",
                      "properties": {
                        "address": {
                          "type": "string"
                        },
                        "latitude": {
                          "type": "number"
                        },
                        "longitude": {
                          "type": "number"
                        }
                      }
                    },
                    "logo_image": {
                      "type": "string"
                    },
                    "logo_redirection_url": {
                      "type": "string"
                    },
                    "auction_image": {
                      "type": "string"
                    },
                    "time_zone": {
                      "type": "string"
                    },
                    "toggle_powered_by_indy": {
                      "type": "boolean"
                    },
                    "hide_auction_lots": {
                      "type": "boolean"
                    },
                    "make_your_auction_private": {
                      "type": "boolean"
                    },
                    "accept_absentee_bid": {
                      "type": "boolean"
                    },
                    "accept_telephone_bid": {
                      "type": "boolean"
                    },
                    "font": {
                    "type": "object"

                    },
                    "button": {
                      "type": "object"
                    },
                    "header": {
                      "type": "object"
                    },
                    "content_area": {
                      "type": "object"
                    },
                    "footer": {
                      "type": "object"
                    },
                    "paddle": {
                      "type": "object"
                    },
                  }
                }
              }
            }
          },
           "responses": {
                "204": {
                  "description": "Update Successful",
                },
                "400": {
                  "description": "Bad Request",
                  "content": {
                    "application/json": {
                      "examples": {
                        "invalid_date": {
                          "value": {
                            "message": "Auction date and time cannot be in the past"
                          }
                        },
                        "generic": {
                          "value": {
                            "message": "Something went wrong. Please try again!"
                          }
                        }
                      }
                    }
                  }
                },
                "500": {
                  "description": "Internal server error",
                  "content": {
                    "application/json": {
                      "examples": {
                        "example1": {
                          "value": {
                            "message": "Internal server error"
                          }
                        }
                      }
                    }
                  }
                }
              },
            "security": [
                {
                  "BearerAuth": []
                }
              ]
            }

      },

     "/lots": {
      "post": {
        "tags": ["Lots"],
        "summary": "Lots create",
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Lots"
              },
              "example": {
                "auction_id": "A2084",
                "seller_email": "sthuthi+testing@7edge.com",
                "title1": "Title1",
                "title2": "title2",
                "description": "<p>description</p>",
                "reserve": 1000,
                "low_estimate": 1000,
                "high_estimate": 20000,
                "shipping_details": "details",
                "current_bid": 0,
                "tags": ["test"],
                "images": [
                  {
                    "url": "DomainName/Auctions/lots/images/9e332f42-e245-05cd-0ec1-74e3b65b136a/sea.webp",
                    "feature": true
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                },
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Lot created successfully"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation failed",
            "content": {
              "application/json": {
                "examples": {
                  "example2": {
                    "value": {
                      "message": "Please fill all the required fields"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Auction not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "examples": {
                  "example1": {
                    "value": {
                      "message": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/list-lots": {
        "get": {
      "tags": [
        "Lots"
      ],
      "summary": "Listing lots",
      "description": "Listing lots",
      "parameters": [
        {
          "name": "auction_id",
          "in": "query",
          "description": "to determine the which auction lots to be displayed ",
          "schema": {
            "type": "string"
          },
          "example": "A0012"
        },
        {
          "name": "sort_by",
          "in": "query",
          "description": "Sort by key",
          "schema": {
            "type": "string"
          },
          "example": "title1"
        },
        {
          "name": "sort_order",
          "in": "query",
          "description": "ascending or descending",
          "schema": {
            "type": "string"
          },
          "example": "descending"
        },
        {
          "name": "page",
          "in": "query",
          "description": "Page number",
          "schema": {
            "type": "integer"
          },
          "example": 1
        },
        {
          "name": "per_page",
          "in": "query",
          "description": "per page documents documents",
          "schema": {
            "type": "string"
          },
          "example": "2"
        },
        {
          "name": "search_keyword",
          "in": "query",
          "description": "ascending or descending",
          "schema": {
            "type": "string"
          },
          "example": "eum"
        }

      ],
      "responses": {
        "200": {
          "description": "Successfully retrieved lots",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": { 
                  "data": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "schema": {
                          "$ref": "#/components/schemas/Lots"
                      }
                      }
                    }
                  },
                  "total_records_found": {
                    "type": "integer"
                  },
                  "total_lots": {
                    "type": "integer"
                  },
                  "current_page": {
                    "type": "integer"
                  },
                  "total_pages": {
                    "type": "integer"
                  },
                  "number_of_bids":{
                    "type": "integer"
                  },
                  "sum_current_bid":{
                    "type": "integer"
                  },
                  "total selling":{
                    "type": "integer"
                  }
                }
              },
              "example": {
                "data": [
                  {

                    "auction_id":"A0012",
                    "seller_email":"anusha.k+indyauction@7edge.com",
                    "lot_number": 0,
                    "lot_title":"platinum diamond ring",
                    "starting_bid":2000,
                    "current_bid":3000,
                    "Top_bidder":"sandhyashri",
                    "images":[{"url": "abcdefghijklmnopqrstuvwxyz.com","feature": true }],
                    "title1":"ring",
                    "title2":"ghj",
                    "description":"",
                    "starting_price":1999,
                    "low_estimate":3000,
                    "high_estimate":20000,
                    "shipping_details":"Bombay",
                    "tags":"jewellery",
                    "start_date": 1701082800000,
                    "end_date": 1701088200000
                  
                }
                ],
                "total_records_found": 1,
                "total_lots": 1,
                "current_page": 1,
                "total_pages": 1
              }
              
            }
          }
        },
        "403": {
          "description": "forbidden",
          "content": {
            "application/json": {
              "examples": {
                "example1": {
                  "value": {
                      "example": "You do not have access to perform this API action"
                    
                  }
                }    
              }
            }
          }
        },
        "500": {
          "description": "Internal Server Error",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string",
                    "example": "Internal server error"
                  }
                }
              }
            }
          }
        }
      },
      "security":[
        {
          "BearerAuth": []
        }
      ]
      }
      }
    },
    "/list-lots": {
      "get": {
      "tags": [
        "Lots"
      ],
      "summary": "Listing lots",
      "description": "Listing lots",
      "parameters": [
        {
          "name": "auction_id",
          "in": "query",
          "description": "to determine the which auction lots to be displayed ",
          "schema": {
            "type": "string"
          },
          "example": "A0012"
        },
        {
          "name": "sort_by",
          "in": "query",
          "description": "Sort by key",
          "schema": {
            "type": "string"
          },
          "example": "title1"
        },
        {
          "name": "sort_order",
          "in": "query",
          "description": "ascending or descending",
          "schema": {
            "type": "string"
          },
          "example": "descending"
        },
        {
          "name": "page",
          "in": "query",
          "description": "Page number",
          "schema": {
            "type": "integer"
          },
          "example": 1
        },
        {
          "name": "per_page",
          "in": "query",
          "description": "per page documents documents",
          "schema": {
            "type": "string"
          },
          "example": "2"
        },
        {
          "name": "search_keyword",
          "in": "query",
          "description": "ascending or descending",
          "schema": {
            "type": "string"
          },
          "example": "eum"
        }

      ],
      "responses": {
        "200": {
          "description": "Successfully retrieved lots",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": { 
                  "data": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "schema": {
                          "$ref": "#/components/schemas/Lots"
                      }
                      }
                    }
                  },
                  "total_records_found": {
                    "type": "integer"
                  },
                  "current_page": {
                    "type": "integer"
                  },
                  "total_pages": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "data": [
                  {
                    "lot_number": 1,
                    "images":[{"url": "abcdefghijklmnopqrstuvwxyz.com","feature": true }],
                    "title1":"ring",
                    "title2":"ghj",
                    "reserve":1999,
                    "number_of_absentee_bids": 0,
                    "number_of_telephone_bids": 0,
                }
                ],
                "total_records_found": 1,
                "current_page": 1,
                "total_pages": 1
              }
              
            }
          }
        },
        "403": {
          "description": "forbidden",
          "content": {
            "application/json": {
              "examples": {
                "example1": {
                  "value": {
                      "example": "You do not have access to perform this API action"
                    
                  }
                }    
              }
            }
          }
        },
        "404": {
          "description": "Not Found",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string",
                    "example": "Auction not found"
                  }
                }
              }
            }
          }
        },
        "500": {
          "description": "Internal Server Error",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string",
                    "example": "Internal server error"
                  }
                }
              }
            }
          }
        }
      },
      "security":[
        {
          "BearerAuth": []
        }
      ]
      }
      }
  },
  "components": {
    "schemas": {
      "Auction": {
        "type": "object",
        "properties": {
          "seller_email": {
            "type": "string"
          },
          "auction_id": {
            "type": "string"
          },
          "template_name": {
            "type": "string"
          },
          "note": {
            "type": "string"
          },
          "menu_links": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                },
                "link_url": {
                  "type": "string"
                },
                "dropdown": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "title": {
                        "type": "string"
                      },
                      "link_url": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "auction_type": {
            "type": "string"
          },
          "accept_absentee_bid": {
            "type": "boolean"
          },
          "accept_telephone_bid": {
            "type": "boolean"
          },
          "location": {
            "type": "object",
            "properties": {
              "latitude": {
                "type": "number"
              },
              "longitude": {
                "type": "number"
              },
              "address": {
                "type": "string"
              }
            }
          },
          "logo_image": {
            "type": "string"
          },
          "logo_redirection_url": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "auction_image": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "currency": {
            "type": "string"
          },
          "start_date": {
            "type": "number"
          },
          "registration_type": {
            "type": "string"
          },
          "add_buyer_fees": {
            "type": "number"
          },
          "time_zone": {
            "type": "string"
          },
          "faq": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "question": {
                  "type": "string"
                },
                "answer": {
                  "type": "string"
                }
              }
            }
          },
          "terms_and_condition": {
            "type": "string"
          },
          "publish_auction_result": {
            "type": "boolean"
          },
          "toggle_powered_by_indy": {
            "type": "boolean"
          },
          "hide_auction_lots": {
            "type": "boolean"
          },
          "make_your_auction_private": {
            "type": "boolean"
          },
          "passcode": {
            "type": "string"
          },
          "font": {
            "type": "object"
          },
          "button": {
            "type": "object"
          },
          "header": {
            "type": "object"
          },
          "content_area": {
            "type": "object"
          },
          "footer": {
            "type": "object"
          },
          "paddle": {
            "type": "object"
          },
          "status": {
            "type": "string"
          }
        }
      },
      "Lots": {
        "type": "object",
        "properties": {
          "auction_id": {
            "type": "string"
          },
          "seller_email": {
            "type": "string"
          },
          "lot_number": {
            "type": "integer"
          },
          "lot_title": {
            "type": "string"
          },
          "images": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                },
                "feature": {
                  "type": "boolean"
                }
              }
            }
          },
          "title1": {
            "type": "string"
          },
          "title2": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "reserve": {
            "type": "integer"
          },
          "low_estimate": {
            "type": "integer"
          },
          "high_estimate": {
            "type": "integer"
          },
          "shipping_details": {
            "type": "string"
          },
          "start_date": {
            "type": "number"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header",
        "description": "Bearer Token"
      }
    }
  }
}
